language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

services:
  - docker

script: make test

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux