---

hosts:
  - address: 127.0.0.1
    checkCommand: check_ping # Mandatory
    checkCommandArgs:
      - 3000,80%
      - 5000,100%
    checkPeriod: 24x7
    contacts: # Specify either contacts or contactGroups but not both
      - nagiosxiadmin
    # contactGroups: # Specify either contacts or contactGroups but not both
    #   - admins
    hostName: machineA # Mandatory
    maxCheckAttempts: 2
    notificationInterval: 5
    notificationPeriod: 24x7
  # - address: ...
  #   ....