---

services:
  - checkCommand: check_ping # Mandatory
    checkCommandArgs:
      - 3000,80%
      - 5000,100%
    checkInterval: 5
    checkPeriod: 24x7
    contacts: # Specify either contacts or contactGroups but not both
      - nagiosxiadmin
    # contactGroups:
    #   - admins
    hostName: machineA # Mandatory
    maxCheckAttempts: 2
    notificationInterval: 5
    notificationPeriod: 24x7
    retryInterval: 5
    serviceDescription: This is a ping service
  # - checkCommand: ...
  #   ....