---

# Be careful ! Every field must be a string !
services:
  - checkCommand: check_ping
    checkCommandArgs:
      - 3000,80%
      - 5000,100%
    checkInterval: "5"
    checkPeriod: 24x7
    contacts: 
      - nagiosadmin
    contactGroups:
      - admins
    hostName: machineA
    maxCheckAttempts: "2"
    notificationInterval: "5"
    notificationPeriod: 24x7
    retryInterval: "5"
    serviceDescription: This is a ping service
  # - checkCommand: ...
  #   ....