---

# Be careful ! Every field must be a string !
services:
  - checkCommand: check_ping
    checkCommandArgs:
      - 3000,80%
      - 5000,100%
    checkInterval: "5"
    checkPeriod: 24x7
    configName: localhost,hostA # If not specified, will equals to hosts array elements (ex: hostA localhost)
    contacts: 
      - nagiosadmin
    contactGroups:
      - admins
      - xi_contactgroup_all
    displayName: Ping Service
    hostGroups:
      - linux-servers
    hosts:
      - hostA
      - localhost
    maxCheckAttempts: "2"
    notificationInterval: "5"
    notificationPeriod: 24x7
    retryInterval: "5"
    serviceDescription: This is a ping service
    serviceGroups:
      - sg1
      - sg2
    templates:
      - local-service
      - generic-service
# - checkCommand: ...